[package]
name = "music"
version = "0.1.0"
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"

[dependencies]

rodio = "0.11"
structopt = "0.3"

[dependencies.rand]

features = [ "small_rng" ]
version = "0.7"

[dev-dependencies]

pretty_assertions = "0.6"