[package]
name = "music"
version = "0.1.0"
authors = ["deciduously <ben@deciduously.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hound = "3.4"
lazy_static = "1.4"
rand = "0.7"
regex = "1.3"
rodio = "0.10"